name: MetricsLanguages
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            filename: metrics.languages.svg
            plugin_languages: yes
            plugin_languages_indepth: yes
            plugin_languages_sections: recently-used
            plugin_languages_recent_load: 400
            plugin_languages_recent_days: 14