name: MetricsStar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            filename: metrics.star.svg
            plugin_stars: yes
            plugin_stars_limit: 3